### ISSUE TITLE
Tried building (./install; make linux64; make sysgen). Did not populate bin.linux64 as I expected.

### ISSUE THREAD

**Issue by steelewool** [iraf/iraf-v216#4]
Here are the last few lines from make if this helps anyone working with linux64 (@zcsteele, @joequant, @pkgw, @sergiuspro @fedya @jehturner (or any others)

Building support libraries ....
  (Using toplevel directory '/home/steele/git/iraf-v216/' ....)
    Building CFITSIO libs ....done
    **Building Readline libs ....mkpkg: Command not found.**
done
    Building VOClient libs ....done
make[1]: Leaving directory '/home/steele/git/iraf-v216/vendor'
**util/mksysgen: line 60: mkpkg: command not found
util/mksysgen: line 64: mkpkg: command not found
util/mksysgen: line 68: mkpkg: command not found**

Start:  Thu Apr 27 11:09:53 PDT 2017
  End:  Thu Apr 27 11:12:33 PDT 2017

Thu Apr 27 11:12:33 PDT 2017

steele@steele-VirtualBox:~/git/iraf-v216$ ls bin.linux64
IB.LNUX.x86_64  IRAF.NET  libcfitsio.a  pkgconfig

**Comment by steelewool** [comment]
I noticed that the mkpkg in vendor/readline doesn't have a if branch for 'linux64'. I'm wondering if anyone knows for sure if it should?

**Comment by joequant** [comment]
Try looking at my build script.

IRAF involves building a series of compilers that build other compilers, so if there is an error, it usually meant that something earlier in the compile failed.

One other build hint is that because IRAF uses a lot of symbolic links, you might have a build work and then stop working because of a symlink thats there.  I've found it necessary to clean out the tree before starting a build.

**Comment by joequant** [comment]
Another problem that I ran into three years ago is that even if you get a compile, it took me a few weeks to get a system to run without crashing.  The reason is that IRAF does some very strange things with lowlevel pointers, and so I had to put in some black magic to modify some internal constants.

See
https://github.com/iraf/iraf-v216/pull/10/commits/d862831be7652d1cc870f8ffc7b4975a97403e85

for an example.

**Comment by iraf** [comment]
The symlinks enable multi-platform builds.  You can remove them, but would
need to then also modify the mkfloat script and mkpkg task to look for
libraries in a bin.<arch> directory instead of 'lib'.

**Comment by RobSteele49** [comment]
For the record, when I pulled in the pull requests made to iraf/iraf-v216 to my branch oleboleUpdates the linux64 build now works and I'm able to run iraf. I have not seen the problems @joequant found three years ago - which I guess is good new.

**Comment by olebole** [comment]
Since the individual problems are covered in other issues (which are going to be closed automatically once the relevant PR is merged), maybe you close this one now?

**Comment by RobSteele49** [comment]
it is up to iraf to close it, but I'll consider this issue closed as we have issues that are directed at the underlying problems.

**Comment by olebole** [comment]
But you can also close it yourself if you consider it solved. I would see no reason to keep it there, since the individual problems are tracked separately.
