### ISSUE TITLE
Which version 2.16 or 2.16.1

### ISSUE THREAD

**Issue by steelewool** [iraf/iraf-v216#6]
The README file references this build as 2.16.1. Does anyone know if that is correct? If it is correct should the repository be renamed to 'iraf-v2161'?

**Comment by iraf** [comment]
The repo contains the frozen IRAF v2.16.1 distribution plus any changes
made on our development servers since that release, so technically it is
'v2.16.2DEV'.  The "v216" name is meant to refer to all v2.16 releases
where a future v2.16.2 release would create a new branch for the version.
I can confirm the various README docs, motd file etc have not had the
version number updated, but you'll find code that post-dates the
v2.16.1EXPORT release date.

**Comment by RobSteele49** [comment]
Thanks for the clarification. I'll consider this issue closed.
